# syntax=docker/dockerfile:1

FROM python:3.9

# Set working directory
WORKDIR /code

COPY requirements.txt .

RUN pip install --no-cache-dir --upgrade -r requirements.txt

COPY . .

EXPOSE 3000

CMD ["gunicorn", "main:app", "-b", ":3000"]